//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisionEntities : DbContext
    {
        public VisionEntities()
            : base("name=VisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Election> Elections { get; set; }
        public virtual DbSet<ElectionType> ElectionTypes { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Role_TB> Role_TB { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voter_TB> Voter_TB { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
