//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public int Voter_id { get; set; }
        public int Election_id { get; set; }
        public int Candidate_id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Election Election { get; set; }
        public virtual Voter_TB Voter_TB { get; set; }
    }
}
