//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voter_TB()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int Id { get; set; }
        public int User_id { get; set; }
        public int Cnic_id { get; set; }
        public int Election_id { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Election Election { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
